# Generated by Django 5.0 on 2023-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=100)),
                ('isCompleted', models.BooleanField(verbose_name=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updateddAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
